### ISSUE TITLE
Add support for lambda (functions as first-class types)

### ISSUE THREAD

**Issue by reddragon** [reddragon/eclisp#17]

**Comment by ghost** [comment]
Yeah I was going to flail my arms around and scream "Lambda doesn't even have support for lambda !" and things like "What an insult !"

I'm bummed because this is one of the better Lisp toys on iOS and it would be great if lambdas were supported.

```
> ((lambda (x) x) 5)
Unknown operator ''
```

Expected result

```
5
```

**Comment by reddragon** [comment]
Thanks for the feedback @naomik . Will take a go at this sometime soon.

**Comment by reddragon** [comment]
This should be fixed now.

```
> (defun add-one (x) (+ x 1))
<Method: add-one>
> (defun twice (f x) (f (f x)))
<Method: twice>
> (twice add-one 2)
4
```

**Comment by reddragon** [comment]
https://github.com/reddragon/lambda/commit/005e9085b9e65a12f3f9a2b97f9eccfdd7b7da57 fixes it.

**Comment by ghost** [comment]
A+++
