### ISSUE TITLE
Passing functions into functions is broken 

### ISSUE THREAD

**Issue by rnml** [reddragon/eclisp#26]
> (defun succ (n) (+ n 1))
> <Method: succ>
> 
> (succ 999)
> 1000
> 
> (succ (succ 999))
> 1001
> 
>  (defun twice (f x) (f (f x)))
> <Method: twice>
> 
> (twice succ 999)
> Unknown operator 'f'

**Comment by reddragon** [comment]
@rnml This is currently not supported. See https://github.com/reddragon/lambda/issues/17

Want to get to this soon.

**Comment by reddragon** [comment]
@rnml This should be fixed now. See https://github.com/reddragon/lambda/commit/005e9085b9e65a12f3f9a2b97f9eccfdd7b7da57 & #17
