### ISSUE TITLE
Code not work

### ISSUE THREAD

**Issue by ghost** [reddragon/eclisp#27]
(defun mod (a b) (cond ((< a b) a)(true mod b (- a b)))) 

> (mod 5 16)
> Undefined variable: a

**Comment by reddragon** [comment]
There is one problem with your call. The inner call mod needs to be surrounded by brackets. Though I couldn't repro the exact error that you received, even without the fix.

```
lambda> (defun mod (a b) (cond ((< a b) a) (true (mod b (- a b)))))
<Method: mod>
lambda> (mod 5 16)
5
lambda> (mod 16 5)
5
lambda>
```

**Comment by ghost** [comment]
> (defun mod (a b) (cond ((< a b) a) (true (mod (- a b) b))))
> <Method: mod>
> 
> (mod 16 5)
> Undefined variable: a

**Comment by ghost** [comment]
in lambda lacks debugger function declaration. until you start the function, you do not learn the error
